### ISSUE TITLE
Site display issues in Firefox

### ISSUE THREAD

**Issue by chocolateboy** [recharts/recharts#176]
**URL**: http://recharts.org/examples/
**OS**: Linux (Arch)
**Firefox**: 47.0.1 (empty profile)

![recharts-wrap](https://cloud.githubusercontent.com/assets/31533/17713217/bc4a6e66-63f1-11e6-8697-5c43beb7bbb7.png)

The first can be fixed by adding `white-space: nowrap` to the `header .logo` rule:

```css
header .logo {
    float: left;
    width: 130px;
    margin-right: 60px;
    font-family: Roboto Mono,Consolas,Liberation Mono,Courier New,Courier,monospace;
    font-weight: 300;
    font-size: 18px;
    white-space: nowrap;
}
```
Not sure what's causing the second. It's the same for all examples. They work fine in JSFiddle.
