### ISSUE TITLE
Render PieChart as inline-block

### ISSUE THREAD

**Issue by avindra** [recharts/recharts#194]
Is there a way to set a `PieChart` to render as an `inline-block` element without using `findDOMNode` hacks?

By default, the wrapper element will display as a block element.

**Comment by avindra** [comment]
To answer my own question, adding this CSS block does it:

```css
.recharts-wrapper {
    display: inline-block;
}
```

Thinking too much in JS :smile:
