### ISSUE TITLE
Skipping the first (lowest) tick

### ISSUE THREAD

**Issue by madshargreave** [recharts/recharts#201]
Hi
 
I'd like to hide the first (lowest) tick on the Y-Axis, is this possible?

I'd also like to apply some right-padding to the ticks, because they're touching the axis. I tried to accomplish this with setting the tick function to a custom react element, but when doing so, no tick is displayed at all.

**Comment by xile611** [comment]
@madshargreave 

 You can add an online jsfiddle example, then maybe I can find the problem.

The first question, you have two methods:
1.Find the css sectors of the tick you want to hide, and set the style of tick by css like the following:
```css
.recharts-wrapper .recharts-y-axis .recharts-cartesian-axis-ticks .recharts-cartesian-axis-tick:first-child {
  display: none;
}
```
2.You can hide the tick by customized function or react element.



The Second question, you have three methods:
1.Set the style of ticks like the following:
```css
.recharts-wrapper .recharts-y-axis .recharts-cartesian-axis-ticks .recharts-cartesian-axis-tick {
  dy: -10;
}
```
2.Set the props `tick` of `YAxis` to be an object like this: `{dx: -10}`.

3.Also by customized function or react element.
