### ISSUE TITLE
Different stroke for Vertical and Horizontal lines in a Cartesian Grid

### ISSUE THREAD

**Issue by choffa** [recharts/recharts#2723]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to be able to specify the colors of the vertical and horizontal lines in a `<CartesianGrid />` seperately so that they can have different colors. My specific use case is that the horizontal lines should have a color depending on some danger level, while the vertical lines should stay gray.

### What does the proposed API look like?
Either allow for several `<CartesianGrid />` components in a Chart, of something like `<CartesianGrid verticalStroke={..} horizontalStroke={..} />`. I prefer the second option as it si similar to the existing `fillHorizontal` and `fillVertical` props

**Comment by tquann286** [comment]
i have a similar problem when stoke color for vertical lines in cartesian grid. Anyone can help?

**Comment by Brookke** [comment]
Similar request, I'd like to have a different stroke array for horizontal vs vertical, so supporting multiple CartesianGrid components would be great

**Comment by Brookke** [comment]
Found a solution

```css
 .recharts-cartesian-grid-horizontal line {
    stroke-dasharray: 0;
  }
 .recharts-cartesian-grid-vertical line {
    stroke-dasharray: 3, 3;
  }
```
