### ISSUE TITLE
DropShadow for line in Area chart

### ISSUE THREAD

**Issue by Tsyklop** [recharts/recharts#4026]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-lmdkw3?file=%2Fsrc%2Findex.js%3A15%2C23)

### Steps to reproduce
open sandbox

### What is expected?
drop shadow for line

### What is actually happening?
no drop shadow

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 120.0.6099.110 |

---
I have figma design what I need, but i cant send image here.

https://www.figma.com/file/MPoBZty0er2WwlpQv2oC7F/BitConvex?type=design&node-id=188%3A1188&mode=dev

How I can do same chart?

**Comment by ckifer** [comment]
Here is a workaround - you could add an id to your charts to make this more specific

```css
path.recharts-curve {
  filter: drop-shadow(0px 4px 4px rgba(8, 8, 8, 0.32))
    drop-shadow(0px -2px 4px rgba(14, 203, 123, 0.32));
}
```

[![Edit recharts-issue-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-dkwjwh)
