### ISSUE TITLE
Chart Title

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#478]
On some Chart objects, [there is a "title" prop](https://github.com/recharts/recharts/blob/master/src/chart/PieChart.js#L53), but this does not manifest into a displayed title (it is unused).

Any chance this can be implemented?

For now, help with placing a <Text/> object would be appreciated... (no x and y location data available).

**Comment by xile611** [comment]
@ZephD Title of charts diff very much, so no plan to implement this feature now.

**Comment by austinpickett** [comment]
@xile611 how do title of charts differ very much? I'm expecting something as simple as:

```
<LineChart title="Chart of PU x UV">...</LineChart>
```

The at the top of the chart, it displays the title. This is pretty standard across all chart presentation (Bar, Circle, Pie, Graph, etc).

**Comment by douglasrcjames** [comment]
Bumping this... how is a simple title not standard?

**Comment by davidchooo** [comment]
Another bump; there should be some simple solution to this by now. I'm having trouble finding any workaround to create a properly centered title for non-static graphs.

**Comment by christiaanwesterbeek** [comment]
A workaround for a centered title

```css
.container {
  display: flex;
  justify-content: center;
  flex-direction: column;
}

.container > h3 {
  margin-left: auto;
  margin-right: auto;
}
```

```jsx
<div className="container">
  <h3>Chart of PU x UV</h3>
  <LineChart>...</LineChart>
</div>
```
