### ISSUE TITLE
Distance between axis labels

### ISSUE THREAD

**Issue by gusdaud** [recharts/recharts#483]
Hi,

Is there a way to increase the distance between the labels and its axis ?
Also how do I change the label font ?

Thanks,

**Comment by gusdaud** [comment]
Not the best solution, but I've found out that this works:

```css
.myChart .recharts-x-axis .recharts-cartesian-axis-tick-value {
  transform: translateY(6px);
}

.myChart .recharts-y-axis .recharts-cartesian-axis-tick-value {
  transform: translateX(-6px);
}
```

Do you think that axis text customization might be something worth of adding in the next versions ?
