### ISSUE TITLE
Question: API documentation on changing the style

### ISSUE THREAD

**Issue by aidanlister** [recharts/recharts#574]
I'm trying to get my graphs looking a bit more like Google's Material (material on top, recharts on bottom):

<img width="1172" alt="screen shot 2017-03-15 at 10 45 53 pm" src="https://cloud.githubusercontent.com/assets/54896/23947408/c3c54db4-09d2-11e7-9073-9e0df5808748.png">

I want to drop the ticklines, set a default font, color, font-aliasing, and move the graph over to the right ... are these sorts of things possible?

**Comment by xile611** [comment]
1. Drop ticklines

```jsx
<XAxis tickLine={false}  />
<YAxis tickLine={false}  />
```
2. Set default font, color

```jsx
<XAxis stroke="black" fontFamily="sans-serif">
```

or use css

```css
.recharts-wrapper .recharts-y-axis .recharts-cartesian-axis-tick text {
  font-fanmily: sans-serif;
  fill: black;
}
```


Please check [rechart.org](http://recharts.org/#/en-US/) for more demos.
