### ISSUE TITLE
Possible to omit first (or last) tick label on an axis?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#661]
Is it possible to omit the first (or last) tick label on an axis? The tick should remain and all else should be the same, just without rendering the label itself? The objective is to omit the "0" on the Y axis so it doesn't "collide" with the left-most label on the X axis:

![image](https://cloud.githubusercontent.com/assets/685316/25454990/e1e0b90a-2a93-11e7-9aad-e1e8af319225.png)

**Comment by xile611** [comment]
@Eric24 Use css or customized tick to omit the first tick.

Css just like:

```css

.recharts-x-axis .recharts-cartesian-axis-tick:first-child line {
 stroke: none;
}
.recharts-x-axis .recharts-cartesian-axis-tick:first-child text {
  font-size: 0;
}
```
