### ISSUE TITLE
ActiveFill for point mouseOver on ScatterPlot

### ISSUE THREAD

**Issue by limscoder** [recharts/recharts#706]
## Do you want to request a feature or report a bug?

Feature

## What is the current behavior?

There does not seem to be an option to specify an active fill for points on a ScatterPlot during mouseOver.

## What is the expected behavior?

Way to specify active fill for points.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

0.22.4

**Comment by xile611** [comment]
@limscoder 
You can add css like the following:
```css
.recharts-scatter .recharts-scatter-symbol .recharts-symbols:hover {
   fill: red;
}
```
[Check this demo](http://jsfiddle.net/7khx5nhj/)
