### ISSUE TITLE
How to move wrapper style of chart and tooltip to css ?

### ISSUE THREAD

**Issue by manishjohar** [recharts/recharts#744]
## Do you want to request a feature or report a bug?
feature

**Comment by manishjohar** [comment]
need help here !!!

**Comment by xile611** [comment]
@manishjohar  You can find the className of Tooltip in chrome Elements , just add styles to thiese classNames in css.

```css
.recharts-tooltip-wrapper {
  background-color: red;
  .recharts-default-tooltip {
    //
    .recharts-tooltip-label {
    
    }
    .recharts-tooltip-item-list {
       .recharts-tooltip-item {
        .recharts-tooltip-item-name {}
        .recharts-tooltip-item-separator {} 
        .recharts-tooltip-item-value {}
        .recharts-tooltip-item-unit {}
      }
     }  
  }
}
```
