### ISSUE TITLE
Active Legend Style

### ISSUE THREAD

**Issue by klapouchy** [recharts/recharts#800]
I would like to know if there is a way to add **active** class/state/style to currently clicked/selected legend (without making a completely custom component that's passed via `content`).

Taking one of the examples - http://jsfiddle.net/z9orjuww/ - I would like to change the `pv` or `uv` font color on mouse enter/leave.

**Comment by xile611** [comment]
@klapouchy You can add some style in css like the following:

```css
.recharts-legend-wrapper .recharts-default-legend .recharts-legend-item {
  cursor: pointer;
}
.recharts-legend-wrapper .recharts-default-legend .recharts-legend-item:hover {
  opacity: 0.2;
}
```

[demo](http://jsfiddle.net/5ndwf1sd/)
