### ISSUE TITLE
How to select a specific bar in bar chart

### ISSUE THREAD

**Issue by jdingsc** [recharts/recharts#811]
Hi there, right now I would like to build a simple chart with barchart, what I want is when my mouse entered that exact bar (not the whole barchart), the color of that bar will be changed and the rest remain unchanged, is there any way I can do that?

Thanks so much!

**Comment by xile611** [comment]
@jdingsc You can add the following css:
```css
.recharts-layer.recharts-bar-rectangle .recharts-rectangle:hover {
   fill: red;
}
```

Check [this demo](http://jsfiddle.net/zt61prx6/).
