### ISSUE TITLE
How to increase the space between label text and axis?

### ISSUE THREAD

**Issue by li-xinyang** [recharts/recharts#830]
## Do you want to request a feature or report a bug?

No

## What is the current behavior?

I could not able to change the space between label text and axis

<img width="902" alt="screen shot 2017-08-13 at 20 58 04" src="https://user-images.githubusercontent.com/3349406/29249874-593406c0-806a-11e7-8062-e650bb8bdfd2.png">

Is there an API to change this? Below is my current solution, with changed width of the axis and some CSS styles

```css
.yAxis .recharts-layer.recharts-cartesian-axis-tick text{
  transform: translate(-5px, 0);
}
.xAxis .recharts-layer.recharts-cartesian-axis-tick text {
  transform: translate(0, 10px);
}
```
